### ISSUE TITLE
Change sentence length detection logic

### ISSUE THREAD

**Issue by 2013ZRZ** [JamesOsborn-SE/eat-poop-you-cat-android#47] opened 2024-05-16 12:13 UTC
Change the sentence length detection logic to make it easier for people in languages with no spaces between words to play this game without adding at least three spaces. Such as Chinese, Japanese and Korean, etc.

**Comment by JamesOsborn-SE** [comment] 2024-05-17 23:44
Sounds like a duplicate of #17

**Comment by 2013ZRZ** [comment] 2024-05-18 09:56
That's the sentence detection logic that changes all languages. I mean, in particular languages, the units used for detection are automatically converted to letters, not words.

**Comment by JamesOsborn-SE** [comment] 2024-05-18 22:20
Number of characters is not the same as words, for example "国际象棋" is chess.

**Comment by 2013ZRZ** [comment] 2024-05-19 02:08
Yes. For example, If I type "国际象棋", I will get the following prompt:
![Screenshot_20240519-100313](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/130883435/47026c93-8fd9-4161-972b-15cb0a762a3c)
Otherwise, if I enter "国 际 象 棋", the test will pass:
![Screenshot_20240519-100329](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/130883435/7323cd4e-fb55-49bf-bf53-d4a0be783d91)

**Comment by JamesOsborn-SE** [comment] 2024-07-22 20:59
I've looked into this and there is no easy solution for all languages. I've decided to remove the requirement.

**Closed** 2024-07-22 22:10 UTC
