### ISSUE TITLE
the ability to write in Russian and in other languages

### ISSUE THREAD

**Issue by Wjxfi** [JamesOsborn-SE/eat-poop-you-cat-android#10] opened 2023-06-30 12:01 UTC

**Comment by JamesOsborn-SE** [comment] 2023-06-30 22:51
Seems like a duplicate of issue #9

**Comment by JamesOsborn-SE** [comment] 2023-07-02 21:14
You can change the language on the device to be what you need. It's an android system change.  That's independent of any app.: 
![image](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/3580335/d3e1b742-214f-4cb1-b3ff-694a0335132a)

**Comment by JamesOsborn-SE** [comment] 2023-07-02 21:15
Never mind I see.. This is a bug..

**Comment by JamesOsborn-SE** [comment] 2023-07-05 16:20
fixed in v1.0.4

**Closed by JamesOsborn-SE** 2023-07-05 16:20 UTC
Labels: bug
